# action.yml
name: Build Meteor Mongo from SRC

on: push
# return to release later
#  release:
#    types: [created]

jobs:
  build:
    runs:
      using: 'docker'
      image: 'Dockerfile'
    steps:
      - name: Checkout master
        uses: actions/checkout@v2.3.1
      - name: Run builder
        run: ./run-builder.sh
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.tgz'
